#include <ostream>
#include <iostream>
int main() {
    std::cout << "hi" << std::endl;
    return 0;
}

/*It should take two command line arguments. 
The first argument denotes the name of the file containing the description of the grammar. 
The second argument denotes the name of the file containing the input strings that we want to feed into the grammar.

The program should be able to read and “parse” the grammar; what I mean by this is that it should be able to identify what the variables, terminals, 
rules, and start variable of the grammar are. Your program should print out all of this info (see below for the format of this output).

The program should go through each string in the second file and print out whether that string is generated by the grammar. 
It should use the algorithm described in Sipser to do this. If you use any other algorithm/approach to test membership, you will not receive any credit.
*/